# Template Dependabot configuration file
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for Cargo (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"

  # Maintain dependencies for Dev Container Features
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"

  # Maintain dependencies for Gradle (Java/Kotlin)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"

  # Maintain dependencies for Maven (Java/Kotlin)
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"

  # Maintain dependencies for npm (Node.js/JavaScript)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"
    versioning-strategy: increase
    ignore:
      - dependency-name: "express"
        versions: [">= 5.0.0"] # Ignore express v5.x and higher

  # Maintain dependencies for pip (Python)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"
    versioning-strategy: increase

  # Maintain dependencies for Terraform
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 20
    assignees:
      - "hugojosefson"
    commit-message:
      prefix: "chore"
