name: bump-deps

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: hasundue/molt-action@v1
        with:
          branch: "bump-deps"
          token: '${{ secrets.BUMP_DEPS_TOKEN }}'
