name: release and publish
on:
  push:
    branches:
      - main

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch "main"

      - name: Create and push release commit, tag
        run: deno task release

      - name: Publish to jsr.io (pretend)
        run: deno publish --dry-run
